version: '3.9'
services:
 kratos:
  image: oryd/kratos:v0.7.0-alpha.1
  ports:
    - '4433:4433' # public
    - '4434:4434' # admin
  restart: unless-stopped
  environment:
    - DSN=${VACHAN_AUTH_DATABASE}
    - LOG_LEVEL=trace
  command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
  volumes:
    # - type: volume
    #   source: kratos-sqlite
    #   target: /var/lib/sqlite
    #   read_only: false
    - type: bind
      source: ./Kratos_config/email-password
      target: /etc/config/kratos
  expose:
    - 4434
    - 4433
  networks:
    - my-network

 vachan-db:
  image: postgres:12.7
  healthcheck:
   test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
   timeout: 45s
   interval: 10s
   retries: 10
  restart: always
  environment: 
   - POSTGRES_USER=${VACHAN_POSTGRES_USER:-postgres}
   - POSTGRES_PASSWORD=${VACHAN_POSTGRES_PASSWORD:-password}
   - POSTGRES_DB=${VACHAN_POSTGRES_DATABASE:-vachan_dev}
   - POSTGRES_HOST_AUTH_METHOD=trust
  logging:
   options:
    max-size: 10m
    max-file: "3"
  expose:
   - 5432
  ports:
   # HOST:CONTAINER
   - "5433:5432"
  networks:
   - my-network
  volumes: 
   # - ${VACHAN_POSTGRES_DATA_DIR:-./pgdata}:/var/lib/postgresql/data
   - vachan-db-vol:/var/lib/postgresql/data
   - ./db/csvs:/csvs
   - ./db/seed_DB.sql:/docker-entrypoint-initdb.d/seed_DB.sql

# vachan-api app
 vachan-api:
  build:
   context: .
   dockerfile: Dockerfile
  healthcheck:
   timeout: 45s
   interval: 10s
   retries: 10
  environment: 
   - VACHAN_POSTGRES_HOST=vachan-db
   - VACHAN_POSTGRES_USER=${VACHAN_POSTGRES_USER:-postgres}
   - VACHAN_POSTGRES_PASSWORD=${VACHAN_POSTGRES_PASSWORD:-password}
   - VACHAN_POSTGRES_DATABASE=${VACHAN_POSTGRES_DATABASE:-vachan_dev}
   - VACHAN_POSTGRES_PORT=5432
   - VACHAN_KRATOS_PUBLIC_URL=http://kratos:4433/
   - VACHAN_KRATOS_ADMIN_URL=http://kratos:4434/
   - VACHAN_SUPER_USERNAME=${VACHAN_SUPER_USERNAME}
   - VACHAN_SUPER_PASSWORD=${VACHAN_SUPER_PASSWORD}
   - VACHAN_TEST_MODE="False"
   - VACHAN_LOGGING_LEVEL=INFO

  volumes:
   # - ./app:/app/app
   - logs-vol:/app/logs
  restart: always
  links:
   - vachan-db
   # - kratos
  expose:
   - 8000
  networks:
   - my-network

# Web Server
 web-server:
  build:
   context: ./nginx
   dockerfile: Dockerfile
  environment:
   domain: ""
  ports:
   - 80:80
   - 443:443
  depends_on:
   - vachan-api
  healthcheck:
   timeout: 45s
   interval: 10s
   retries: 10
  volumes:
    - logs-vol:/var/log/nginx
  networks:
   - my-network

networks:
 my-network:              
volumes:
  vachan-db-vol:
  logs-vol:
  # kratos-sqlite: