version: '3.9'
services:
 vachan-db:
  image: postgres:12.7
  healthcheck:
   test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "uday" ]
   timeout: 45s
   interval: 10s
   retries: 10
  restart: always
  environment: 
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=postgres
   - POSTGRES_HOST_AUTH_METHOD=trust
  logging:
   options:
    max-size: 10m
    max-file: "3"
  expose:
   - 5432
  ports:
   # HOST:CONTAINER
   - "5433:5432"
  networks:
   - my-network
  volumes: 
   - /tmp/postgres-data:/var/lib/postgresql/data
   # All docker files for deplployment and database script
   - ./db/:/docker-entrypoint-initdb.d/
   # Seed file

# vachan-api app
 vachan-api:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: vachan-app
  healthcheck:
   timeout: 45s
   interval: 10s
   retries: 10
  environment: 
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
   - VACHAN_POSTGRES_HOST=${VACHAN_POSTGRES_HOST}
   - VACHAN_POSTGRES_USER=${VACHAN_POSTGRES_USER}
   - VACHAN_POSTGRES_PASSWORD=${VACHAN_POSTGRES_PASSWORD}
   - VACHAN_POSTGRES_DATABASE=${VACHAN_POSTGRES_DATABASE}
   - VACHAN_POSTGRES_PORT=${VACHAN_POSTGRES_PORT}
  volumes:
   - ./app:/app/app
  restart: always
  depends_on:
   - vachan-db
  links:
   - vachan-db:vachan-db
  expose:
   - 5000
  ports:
   - "5000:5000"
  networks:
   - my-network

# Web Server
 web-server:
  build:
   context: ./nginx
   dockerfile: Dockerfile
  environment:
   domain: ""
  ports:
   - 5001:80
   - 5002:443
  volumes:
   - ./nginx:/nginx/
  depends_on:
   - vachan-api
  healthcheck:
   timeout: 45s
   interval: 10s
   retries: 10
  networks:
   - my-network

networks:
 my-network:              
                                                                                                                                                                                                                             