version: '3.9'
services:
 vachan-db:
  image: postgres:12.7
  healthcheck:
<<<<<<< HEAD
   test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
=======
   test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "uday" ]
>>>>>>> af6ebc7bf11f6efd50f86d22fa72e648923af31f
   timeout: 45s
   interval: 10s
   retries: 10
  restart: always
  environment: 
   - POSTGRES_USER=${VACHAN_POSTGRES_USER:-postgres}
   - POSTGRES_PASSWORD=${VACHAN_POSTGRES_PASSWORD:-password}
   - POSTGRES_DB=${VACHAN_POSTGRES_DATABASE:-vachan_dev}
   - POSTGRES_HOST_AUTH_METHOD=trust
  logging:
   options:
    max-size: 10m
    max-file: "3"
  expose:
   - 5432
  ports:
   # HOST:CONTAINER
   - "5433:5432"
  networks:
   - my-network
  volumes: 
   - ${VACHAN_POSTGRES_DATA_DIR:-./pgdata}:/var/lib/postgresql/data
   - ./db/csvs:/csvs
   - ./db/seed_DB.sql:/docker-entrypoint-initdb.d/seed_DB.sql

# vachan-api app
 vachan-api:
  build:
   context: .
   dockerfile: Dockerfile
  healthcheck:
   timeout: 45s
   interval: 10s
   retries: 10
  environment: 
   - VACHAN_POSTGRES_HOST=vachan-db
   - VACHAN_POSTGRES_USER=${VACHAN_POSTGRES_USER:-postgres}
   - VACHAN_POSTGRES_PASSWORD=${VACHAN_POSTGRES_PASSWORD:-password}
   - VACHAN_POSTGRES_DATABASE=${VACHAN_POSTGRES_DATABASE:-vachan_dev}
   - VACHAN_POSTGRES_PORT=5432
   - VACHAN_TEST_MODE=True
  volumes:
   - ./app:/app/app
   - ./logs:/app/logs
  restart: always
  depends_on:
   - vachan-db
  expose:
   - 8000
  networks:
   - my-network

# Web Server
 web-server:
  build:
   context: ./nginx
   dockerfile: Dockerfile
  environment:
   domain: ""
  ports:
   - 80:80
   - 443:443
  depends_on:
   - vachan-api
  healthcheck:
   timeout: 45s
   interval: 10s
   retries: 10
  networks:
   - my-network

networks:
 my-network:              
