version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.7.0-alpha.1
    environment:
      - DSN=${VACHAN_AUTH_DATABASE_1:-postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4}
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - vachan-auth-net

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${VACHAN_KRATOS_DB_USER:-kratos}
      - POSTGRES_PASSWORD=${VACHAN_KRATOS_DB_PASSWORD:-secret}
      - POSTGRES_DB=${VACHAN_KRATOS_DB_NAME:-kratos}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    networks:
      - vachan-auth-net
networks:
 vachan-auth-net:
volumes:
  kratos-sqlite:              
